/** Matriz requisito → ator → tela → API → tabelas → permissão, extraída do código atual. */

export type LinhaRastreabilidade = {
  id: string;
  capacidade: string;
  ator: string;
  tela: string;
  api: string;
  tabelas: string;
  permissao: string;
};

export const MATRIZ_RASTREABILIDADE: LinhaRastreabilidade[] = [
  {
    id: 'auth',
    capacidade: 'Autenticar e encerrar sessão',
    ator: 'Usuário interno (qualquer perfil)',
    tela: '/login',
    api: 'AuthController: POST /auth/login, GET /auth/me, POST /auth/logout',
    tabelas: 'Usuario, Perfil, UsuarioPerfil, Permissao, PerfilPermissao, UsuarioPermissao, UsuarioSecretaria, Secretaria',
    permissao: 'Login é público. As demais rotas exigem sessão (AuthGuard).',
  },
  {
    id: 'contexto',
    capacidade: 'Trocar perfil ativo e secretaria ativa',
    ator: 'Usuário interno',
    tela: '/conta',
    api: 'AuthController: POST /auth/perfil-ativo, POST /auth/secretaria-ativa, POST /auth/change-password',
    tabelas: 'Usuario, Perfil, Secretaria, UsuarioSecretaria',
    permissao: 'Sessão autenticada. A secretaria precisa estar no vínculo do usuário, salvo acesso a todas.',
  },
  {
    id: 'senha',
    capacidade: 'Recuperar e redefinir senha',
    ator: 'Usuário interno',
    tela: '/recuperar-senha, /redefinir-senha',
    api: 'AuthController: POST /auth/forgot-password, POST /auth/reset-password',
    tabelas: 'PasswordResetToken, Usuario',
    permissao: 'Rotas públicas. O token persistido é hash e tem validade.',
  },
  {
    id: 'cco',
    capacidade: 'Acompanhar o centro de controle e o mapa',
    ator: 'Administrador do Sistema, gestor, equipe com leitura operacional',
    tela: '/cco, /cco/unidades/[id]',
    api: 'OperacionalController: GET /operacional/resumo, /secretarias, /bairros, /opcoes-filtro, /unidades, /chamados-mapa',
    tabelas: 'UnidadePublica, Secretaria, Chamado, NaoConformidade, Fiscalizacao',
    permissao: 'OPERACIONAL_READ_KEYS (dashboard.visualizar, chamados.*, fiscalizacoes.executar e matriz.cco._tela.visualizar, entre outras).',
  },
  {
    id: 'dashboard',
    capacidade: 'Consultar indicadores e alertas',
    ator: 'Administrador do Sistema, gestor',
    tela: '/dashboard',
    api: 'MonitoramentoController: GET /monitoramento/dashboard, GET /monitoramento/alertas. A grade de tarefas usa GET /chamado-tarefas/relatorio.',
    tabelas: 'DashboardSnapshot, Chamado, ChamadoTarefa, Fiscalizacao, UnidadePublica',
    permissao: 'dashboard.visualizar. O menu usa a mesma chave ou matriz.dashboard._tela.visualizar.',
  },
  {
    id: 'relatorios',
    capacidade: 'Exportar relatórios operacionais',
    ator: 'Administrador do Sistema, gestor',
    tela: '/relatorios',
    api: 'RelatoriosController: GET /relatorios/export/unidades|chamados|ordens-servico|fiscalizacoes|cronograma-cobertura (csv, pdf, xlsx)',
    tabelas: 'UnidadePublica, Chamado, Fiscalizacao, CronogramaChecagem, Secretaria',
    permissao: 'dashboard.visualizar no controller. Menu Relatórios usa a mesma chave.',
  },
  {
    id: 'abrir',
    capacidade: 'Abrir chamado interno',
    ator: 'Gestor, solicitante interno, equipe de vistoria, perfil externo',
    tela: '/chamados/novo',
    api: 'ChamadosController: GET /chamados/tipos/opcoes, GET /chamados/secretarias/execucao, POST /chamados',
    tabelas: 'Chamado, TipoChamado, TipoChamadoSecretaria, UnidadePublica, Secretaria, Evidencia, ChamadoSequencia',
    permissao: 'CHAMADOS_ABRIR_KEYS: chamados.abrir, chamados.gerenciar, matriz.chamados.abrir_chamado, fiscalizacoes.executar. Perfil EXTERNO só encaminha para secretaria do tipo.',
  },
  {
    id: 'publico',
    capacidade: 'Abrir chamado pelo código da unidade',
    ator: 'Cidadão (sem login)',
    tela: '/chamado/[codigo]',
    api: 'PublicChamadosController: GET /public/tipos-chamado, GET /public/unidades/:codigo, POST /public/unidades/:codigo/chamados',
    tabelas: 'Chamado, UnidadePublica, TipoChamado',
    permissao: 'Sem autenticação. Limite de taxa no controller público.',
  },
  {
    id: 'protocolo',
    capacidade: 'Consultar protocolo público',
    ator: 'Cidadão (sem login)',
    tela: '/chamado/protocolo, /chamado/protocolo/[codigo]',
    api: 'PublicChamadosController: GET /public/chamados/protocolo/:codigo',
    tabelas: 'Chamado',
    permissao: 'Sem autenticação. Limite de taxa.',
  },
  {
    id: 'triagem',
    capacidade: 'Triar, atribuir, planejar e notificar equipe',
    ator: 'Administrador do Sistema, gestor',
    tela: '/chamados',
    api: 'ChamadosController: GET /chamados, PUT /:id/status, /triagem, /atribuicao, /planejamento, /abertura, /observadores, POST /:id/historico, POST /:id/notificar-equipe',
    tabelas: 'Chamado, HistoricoStatus, Equipe, EquipeUsuario, Usuario, ChamadoObservador, TipoChamado',
    permissao: 'chamados.gerenciar. Edição da abertura também aceita chamados.editar_abertura. Escopo pela secretaria ativa. A busca da lista consulta o conjunto do escopo, não só a página visível.',
  },
  {
    id: 'meus',
    capacidade: 'Acompanhar meus chamados e observadores',
    ator: 'Solicitante interno, gestor',
    tela: '/meus-chamados',
    api: 'MeusChamadosController: GET /meus-chamados, GET /:id, PUT|POST|DELETE observadores',
    tabelas: 'Chamado, ChamadoObservador, Usuario',
    permissao: 'meus_chamados.visualizar, chamados.abrir ou chamados.gerenciar. Observadores só por quem abriu.',
  },
  {
    id: 'execucao',
    capacidade: 'Executar chamado em campo',
    ator: 'Equipe de execução, gestor',
    tela: '/execucao, /execucao/[id], /chamados/em-execucao',
    api: 'ChamadosController: GET /chamados/em-execucao, GET /:id/execucao, POST checkin, evidencias, concluir',
    tabelas: 'Chamado, Evidencia, HistoricoStatus, Equipe, Usuario',
    permissao: 'chamados.gerenciar ou chamados.executar. Menu Execução usa as duas.',
  },
  {
    id: 'manual',
    capacidade: 'Registrar execução manual',
    ator: 'Equipe de execução, gestor',
    tela: '/execucao/[id]',
    api: 'ChamadosController: POST /chamados/:id/execucao/manual',
    tabelas: 'Chamado, HistoricoStatus',
    permissao: 'chamados.gerenciar, chamados.executar ou chamados.execucao_manual.',
  },
  {
    id: 'exclusao',
    capacidade: 'Excluir e restaurar chamado',
    ator: 'Administrador do Sistema, gestor com matriz',
    tela: '/chamados',
    api: 'ChamadosController: POST /chamados/:id/exclusao-logica, POST /chamados/:id/restaurar-exclusao',
    tabelas: 'Chamado, Secretaria, Usuario',
    permissao: 'Administrador do Sistema, ou matriz.chamados.excluir_logicamente.excluir e matriz.chamados.restaurar_excluido.alterar. Consulta de excluídos: excluidos_visualizar.',
  },
  {
    id: 'tarefas',
    capacidade: 'Atribuir e acompanhar tarefas do chamado',
    ator: 'Administrador do Sistema, gestor',
    tela: '/chamados (painel da tarefa)',
    api: 'ChamadoTarefasController: GET /chamado-tarefas/por-chamado/:chamadoId, GET /opcoes, POST /chamado-tarefas, PATCH /:id, POST /:id/anexos',
    tabelas: 'ChamadoTarefa, ChamadoTarefaAnexo, Chamado, Secretaria, Equipe, Usuario',
    permissao: 'matriz.chamados.tarefas: visualizar, inserir (criar), alterar (dados de abertura), executar (andamento e conclusão, compatível), excluir (cancelar). Funções extras: tarefas_andamento, tarefas_concluir e tarefas_historico. Administrador do Sistema ignora a matriz. Responsável ou membro da equipe não ganha alterar dados.',
  },
  {
    id: 'tarefas-exec',
    capacidade: 'Tratar tarefa na execução',
    ator: 'Equipe de execução, gestor',
    tela: '/execucao (aba tarefas)',
    api: 'ChamadoTarefasController: GET /chamado-tarefas/execucao, PATCH /chamado-tarefas/:id',
    tabelas: 'ChamadoTarefa, EquipeUsuario, Usuario',
    permissao: 'As mesmas chaves de chamados.tarefas, mais matriz.execucao.tarefas e chamados.tarefas_atribuidas.visualizar. Filtros da aba ficam na sanfona Filtros de tarefas.',
  },
  {
    id: 'tarefas-rel',
    capacidade: 'Relatório de tarefas',
    ator: 'Administrador do Sistema, gestor',
    tela: '/dashboard (grade) e /relatorios (card Gerar)',
    api: 'ChamadoTarefasController: GET /chamado-tarefas/relatorio e /relatorio.csv|pdf|xlsx. capa=simples exporta a grade; o PDF formal usa o cabeçalho SIGMA.',
    tabelas: 'ChamadoTarefa, Chamado, Secretaria, Equipe',
    permissao: 'chamados.gerenciar, dashboard.visualizar ou matriz de relatórios/tarefas. O escopo de secretaria do usuário é aplicado na consulta.',
  },
  {
    id: 'mobile',
    capacidade: 'Realizar vistoria de campo',
    ator: 'Equipe de execução',
    tela: '/mobile',
    api: 'MobileController: GET /mobile/field-package, /vistorias-programadas, /unidades/:id/chamados-pendentes',
    tabelas: 'Fiscalizacao, Checklist, ChecklistVersao, ChecklistItem, UnidadePublica, CronogramaChecagem, Chamado',
    permissao: 'fiscalizacoes.executar. Menu Vistoria usa a mesma chave ou matriz.vistoria_campo.',
  },
  {
    id: 'sync',
    capacidade: 'Sincronizar vistoria offline',
    ator: 'Equipe de execução',
    tela: '/mobile',
    api: 'MobileController: POST /mobile/sync/fiscalizacoes',
    tabelas: 'OfflineSyncEvent, Fiscalizacao, RespostaChecklist, Evidencia, NaoConformidade',
    permissao: 'fiscalizacoes.executar.',
  },
  {
    id: 'vistorias',
    capacidade: 'Consultar vistorias realizadas',
    ator: 'Gestor, equipe, administrador',
    tela: '/vistorias',
    api: 'FiscalizacoesController: GET /fiscalizacoes, GET /fiscalizacoes/:id, GET /fiscalizacoes/:id/pdf',
    tabelas: 'Fiscalizacao, RespostaChecklist, Evidencia, NaoConformidade, UnidadePublica, Usuario',
    permissao: 'fiscalizacoes.executar, dashboard.visualizar ou chamados.gerenciar.',
  },
  {
    id: 'vistoria-manual',
    capacidade: 'Lançar ou imprimir vistoria manual',
    ator: 'Equipe de execução',
    tela: '/vistorias, /mobile',
    api: 'FiscalizacoesController: GET /fiscalizacoes/opcoes-manuais, POST /lancamento-manual, POST /imprimir-manual',
    tabelas: 'Fiscalizacao, ChecklistVersao, UnidadePublica, Usuario',
    permissao: 'fiscalizacoes.executar.',
  },
  {
    id: 'checklists',
    capacidade: 'Modelar e publicar checklists',
    ator: 'Administrador do Sistema, gestor com a permissão',
    tela: '/checklists, /checklists/[id]',
    api: 'ChecklistsController: GET|POST|PUT|DELETE /checklists, POST /:id/versions, POST /versions/:versionId/publish',
    tabelas: 'Checklist, ChecklistVersao, ChecklistItem, ChecklistTipoChamado, CategoriaVistoria, TipoProprio',
    permissao: 'checklists.gerenciar ou matriz.checklists._tela / gerenciar.',
  },
  {
    id: 'cronograma',
    capacidade: 'Programar cronograma de checagem',
    ator: 'Administrador do Sistema, gestor',
    tela: '/cronograma',
    api: 'CronogramaController: GET /cronograma, GET /calendario, POST, PUT /:id, DELETE /:id',
    tabelas: 'CronogramaChecagem, CronogramaChecagemResponsavel, Checklist, UnidadePublica, Usuario',
    permissao: 'cronograma.visualizar/inserir/alterar/excluir, legado dashboard.visualizar e checklists.gerenciar, ou matriz.cronograma.',
  },
  {
    id: 'nc',
    capacidade: 'Vincular ou baixar não conformidade',
    ator: 'Administrador do Sistema, gestor',
    tela: '/cco',
    api: 'OperacionalController: POST /operacional/nao-conformidades/:id/vincular-chamado, POST /:id/baixa',
    tabelas: 'NaoConformidade, Chamado, Evidencia, UnidadePublica',
    permissao: 'dashboard.visualizar ou chamados.gerenciar.',
  },
  {
    id: 'documentos',
    capacidade: 'Consultar documentos e gerar PDF',
    ator: 'Gestor, equipe, solicitante, administrador',
    tela: '/documentos',
    api: 'DocumentosController: GET /documentos, GET /:id, GET /chamados-busca, GET /:id/pdf/original, GET /:id/pdf/assinado, POST /:id/gerar-pdf, PATCH /:id/vinculos, /respostas, POST /:id/concluir',
    tabelas: 'Documento, DocumentoChamado, DocumentoResposta, ChecklistItem, Chamado, Fiscalizacao',
    permissao: 'documentos.visualizar ou documentos.administrar (módulo). PDF relacionado também aceita dashboard, chamados e fiscalização. Vínculo de avulso em rascunho: documentos.criar_avulso. Depois da conclusão: documentos.editar_vinculo.',
  },
  {
    id: 'avulso',
    capacidade: 'Criar documento avulso',
    ator: 'Administrador do Sistema, gestor',
    tela: '/documentos',
    api: 'DocumentosController: GET /documentos/checklists-avulso, GET /documentos/chamados-busca, POST /documentos/avulso',
    tabelas: 'Documento, DocumentoChamado, DocumentoResposta, Checklist, ChecklistVersao, Secretaria, Chamado',
    permissao: 'documentos.criar_avulso, documentos.administrar ou matriz.documentos.avulso.inserir.',
  },
  {
    id: 'ass-ext',
    capacidade: 'Coletar assinatura externa',
    ator: 'Gestor, equipe autorizada, administrador',
    tela: '/documentos',
    api: 'DocumentosController: POST /documentos/:id/assinatura, /assinatura-pendente, /cancelar-assinado',
    tabelas: 'Documento, DocumentoAssinatura',
    permissao: 'documentos.coletar_assinatura ou documentos.administrar. Cancelamento: documentos.cancelar_assinado. Aviso e erro de campo ficam na frente do modal.',
  },
  {
    id: 'ass-int',
    capacidade: 'Disponibilizar e assinar internamente',
    ator: 'Gestor (disponibiliza); destinatário interno (assina)',
    tela: '/documentos, aviso em /login',
    api: 'DocumentosController: GET /pendencias-resumo, GET /minhas-pendencias-assinatura, GET /signatarios-internos, POST /:id/disponibilizar-assinatura, POST /:id/assinatura-interna, POST pedidos-assinatura/:id/retirar|recusar',
    tabelas: 'DocumentoAssinaturaPedido, DocumentoAssinatura, Documento, Usuario',
    permissao: 'documentos.disponibilizar_assinatura ou documentos.assinar_interno (e as chaves de matriz correspondentes). Administrador e documentos.administrar também passam.',
  },
  {
    id: 'validar',
    capacidade: 'Validar documento publicamente',
    ator: 'Cidadão (sem login)',
    tela: '/documento/validar, /documento/validar/[codigo]',
    api: 'PublicDocumentosController: GET /public/documentos/validar/:codigo, GET /public/documentos/validar-por-documento',
    tabelas: 'Documento, DocumentoAssinatura',
    permissao: 'Sem autenticação. Exige código verificador. Limite de taxa.',
  },
  {
    id: 'admin-cad',
    capacidade: 'Manter cadastros administrativos',
    ator: 'Administrador do Sistema e perfis com a aba',
    tela: '/admin (Secretarias, Próprios, Usuários, Equipes, Cargos, Tipos, Categorias)',
    api: 'AdminController: /admin/secretarias, /unidades, /usuarios, /equipes, /cargos, /tipos-chamado, /tipos-proprio, /categorias-vistoria',
    tabelas: 'Secretaria, UnidadePublica, Usuario, Equipe, EquipeUsuario, Cargo, TipoChamado, TipoChamadoSecretaria, TipoProprio, CategoriaVistoria',
    permissao: 'Matriz admin.<aba>.<ação> ou chaves legadas (usuarios.gerenciar, secretarias.gerenciar, unidades.gerenciar). Administrador do Sistema vê todas as abas.',
  },
  {
    id: 'admin-perm',
    capacidade: 'Configurar perfis e matriz de permissões',
    ator: 'Administrador do Sistema',
    tela: '/admin (Permissões)',
    api: 'AdminController: /admin/permissoes/catalogo, /admin/perfis, /perfis/configuraveis, /perfis/:id/matriz, /usuarios/:id/matriz',
    tabelas: 'Perfil, Permissao, PerfilPermissao, UsuarioPermissao, UsuarioPerfil',
    permissao: 'Aba permissoes: permissoes.gerenciar ou usuarios.gerenciar, ou matriz.admin.permissoes.',
  },
  {
    id: 'webmap',
    capacidade: 'Importar unidades do webmap',
    ator: 'Administrador do Sistema',
    tela: '/admin (Importação)',
    api: 'AdminImportController: /admin/importacao/webmap/status|preview|apply|sync|sync-all e /secretarias/sync',
    tabelas: 'UnidadePublica, WebmapImport, TipoProprio, Secretaria',
    permissao: 'Aba importacao: unidades.gerenciar ou usuarios.gerenciar, ou matriz.admin.importacao.',
  },
  {
    id: 'auditoria',
    capacidade: 'Consultar e configurar auditoria',
    ator: 'Administrador do Sistema',
    tela: '/admin (Logs)',
    api: 'AdminController: GET /admin/auditoria/logs, GET|PUT /admin/auditoria/config',
    tabelas: 'LogAuditoria, AuditoriaConfig, Usuario',
    permissao: 'auditoria.visualizar ou usuarios.gerenciar, ou matriz.admin.auditoria. Alterar a config exige alterar ou executar.',
  },
  {
    id: 'backup',
    capacidade: 'Configurar e executar backup',
    ator: 'Administrador do Sistema',
    tela: '/admin (Backup S3)',
    api: 'BackupController: GET|PUT /admin/backup, POST /admin/backup/run, GET /objects, POST /restore',
    tabelas: 'BackupS3Config',
    permissao: 'Aba backup, em geral usuarios.gerenciar ou matriz.admin.backup. A chave secreta não sai na API.',
  },
  {
    id: 'email',
    capacidade: 'Configurar e-mail transacional',
    ator: 'Administrador do Sistema',
    tela: '/admin (E-mail)',
    api: 'EmailConfigController: GET|PUT /admin/email, POST /admin/email/teste',
    tabelas: 'ConfiguracaoEmail',
    permissao: 'Aba email, em geral usuarios.gerenciar ou matriz.admin.email. A senha SMTP não sai na API.',
  },
  {
    id: 'integracoes',
    capacidade: 'Monitorar sincronização e integrações',
    ator: 'Administrador do Sistema',
    tela: '/integracoes',
    api: 'IntegracoesController: GET /integracoes/eventos, POST /notificar, POST /sync/retry, POST /sync/:id/retry|ignorar',
    tabelas: 'OfflineSyncEvent, Usuario',
    permissao: 'auditoria.visualizar ou matriz.integracoes._tela/monitorar. Reprocessar exige a ação executar da matriz.',
  },
  {
    id: 'push',
    capacidade: 'Inscrever alertas no navegador',
    ator: 'Gestor com dashboard',
    tela: '/dashboard',
    api: 'NotificacoesController: GET /notificacoes/push/vapid-public-key, POST /subscribe, /unsubscribe, POST /alertas/disparar',
    tabelas: 'PushSubscription, Usuario',
    permissao: 'dashboard.visualizar nas rotas autenticadas de push.',
  },
  {
    id: 'lgpd',
    capacidade: 'Anonimizar usuário e reter auditoria',
    ator: 'Administrador do Sistema',
    tela: '/admin (bloco LGPD quando a aba de usuários pode excluir)',
    api: 'LgpdController: POST /lgpd/usuarios/:id/anonymize, POST /lgpd/auditoria/purge',
    tabelas: 'Usuario, LogAuditoria',
    permissao: 'usuarios.gerenciar.',
  },
  {
    id: 'storage',
    capacidade: 'Servir evidências e arquivos locais',
    ator: 'Usuário autenticado que já obteve a URL',
    tela: 'Embutido na execução, vistoria, chamado e documento',
    api: 'StorageController: GET /storage/* (somente driver local). HealthController: GET /health/storage',
    tabelas: 'Evidencia, Documento, Chamado, ChamadoTarefaAnexo, DocumentoAssinatura',
    permissao: 'AuthGuard. O binário não fica no PostgreSQL; a tabela guarda url e storageKey.',
  },
  {
    id: 'saude',
    capacidade: 'Sondar saúde da API e do banco',
    ator: 'Operação (sem tela no produto)',
    tela: 'Sem tela. Sonda HTTP.',
    api: 'HealthController: GET /, GET /health, GET /health/db, GET /health/storage',
    tabelas: 'Nenhuma tabela de negócio. /health/db consulta o PostgreSQL via Prisma.',
    permissao: 'Rotas de saúde sem o guard de permissão de tela.',
  },
];
